### ISSUE TITLE
Constructors? Destructors?

### ISSUE THREAD

**Issue by cculianu** [michaeljclark/zhashmap#1]
https://github.com/michaeljclark/zhashmap/blob/2fc3b36acbf4427b47c68ee7bc797818f07bf7d0/src/hashmap.h#L183

`clear()` doesn't seem to call any destructors above... 

Similarly, erase just assigns `Value(0)` to the element.

So I take it this data structure is only to be used with basic plain old data integer types and nothing else?

**Comment by cculianu** [comment]
Suggestion: For now, restricting the Key and Value types to types satisfying this:

https://en.cppreference.com/w/cpp/types/is_pod

**Comment by larkmjc** [comment]
Adding is_pod makes sense. should also add a note to the readme to indicate this.

**Comment by larkmjc** [comment]
i've updated the code to always call the copy constructor when copying (instead of using memcpy) and to call the destructor when clearing and during destruction but given the design has a bitmap that indicates which entries are occupied, the code only calls destructor for items labeled as occupied in the bitmap. in fact with this change it does slightly less copying because we only copy the bitmap and any populated entries rather than the entire allocation. it needs some testing but it could potentially be even faster. here is the change: https://github.com/michaeljclark/ethical_hashmap/commit/b95632dd18530c52845cf0f56dc9417bbae7e9ae

I'll leave this issue open until i've had further feedback from verification as to whether this properly solves this issue, as previously I was only testing with POD types. we no longer clear the values with Value(0) and instead just call the destructor which would be a no-op for POD types, so this may also speed things up. sorry it took so long. I just thought I might as well attempt to work properly for non POD types. this applies to all four classes: hash set, hash map, linked hash set and linked hash map.

**Comment by michaeljclark** [comment]
closing this issue given the code now calls copy constructors and destructors, noting that on construction the container is empty and we have not allocated any memory to items; the bitmap is clear, thus we do not call default initializers in the constructor, instead we call copy constructors when storing values into the map, or which copying allocated slots, unlike an array where we would expect to default initialize the whole array. this approach gives us a performance advantage.

**Comment by larkmjc** [comment]
closing this issue given the code now calls copy constructors and destructors, noting that on construction the container is empty and we have not allocated any memory to items; the bitmap is clear, thus we do not call default initializers in the constructor, instead we call copy constructors when storing values into the map, or when copying allocated slots, unlike an array where we would expect to default initialize the whole array. this approach gives us a performance advantage.
